development:
  cloud_name: bookreview123
  api_key: '661993266896223'
  api_secret: cY014MFHGOptrhJCRWNO5BjBD9g
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: bookreview123
  api_key: '661993266896223'
  api_secret: cY014MFHGOptrhJCRWNO5BjBD9g
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: bookreview123
  api_key: '661993266896223'
  api_secret: cY014MFHGOptrhJCRWNO5BjBD9g
  enhance_image_tag: true
  static_file_support: false
